### ISSUE TITLE
TraceLogger extension causing a hang on VS startup and other scenarios

### ISSUE THREAD

**Issue by prasethu** [madskristensen/TraceLogger#3]
Visual Studio: Visual Studio 2017
This extension: 1.0.4

Description
This extension is causing a hang for some customers. 

Please see this issue for details including a DMP: 
[https://developercommunity.visualstudio.com/content/problem/52548/visual-studio-hangs-on-startup-when-start-page-is.html](https://developercommunity.visualstudio.com/content/problem/52548/visual-studio-hangs-on-startup-when-start-page-is.html)

Here's the stack trace:

>	ntdll.dll!_NtWaitForMultipleObjects@20()	Unknown
 	KERNELBASE.dll!WaitForMultipleObjectsEx(unsigned long nCount, void * const * lpHandles, int bWaitAll, unsigned long dwMilliseconds, int bAlertable) Line 1551	C
 	combase.dll!MTAThreadWaitForCall(CSyncClientCall * pClientCall, WaitForCallReason reason, unsigned long dwRetryTimeout) Line 7290	C++
 	combase.dll!CSyncClientCall::SendReceive2(tagRPCOLEMESSAGE * pMessage, unsigned long * pstatus) Line 5764	C++
 	combase.dll!CSyncClientCall::SendReceive(tagRPCOLEMESSAGE * pMessage, unsigned long * pulStatus) Line 823	C++
 	combase.dll!NdrExtpProxySendReceive(void * pThis, _MIDL_STUB_MESSAGE * pStubMsg) Line 1965	C++
 	rpcrt4.dll!NdrClientCall2()	Unknown
 	combase.dll!ObjectStublessClient(void * ParamAddress, long Method) Line 217	C++
 	combase.dll!_ObjectStubless@0() Line 171	Unknown
 	Microsoft.VisualStudio.Shell.Interop.ni.dll!6f61cce5()	Unknown
 	[Frames below may be incorrect and/or missing, native debugger attempting to walk managed call stack]	
 	Microsoft.VisualStudio.Shell.Interop.ni.dll!6f61cce5()	Unknown
 	[Managed to Native Transition]	
 	TraceLogger.dll!TraceLogger.OutputWindowTraceListener.Write(string message)	Unknown
 	TraceLogger.dll!TraceLogger.OutputWindowTraceListener.WriteLine(string message)	Unknown
 	System.dll!System.Diagnostics.TraceInternal.WriteLine(string message)	Unknown
 	Microsoft.VisualStudio.Services.WebApi.dll!Microsoft.VisualStudio.Services.WebApi.VssRequestTimerTrace.TraceResponse(System.Net.Http.HttpResponseMessage response) Line 85	C#
 	Microsoft.VisualStudio.Services.WebApi.dll!Microsoft.VisualStudio.Services.WebApi.HttpMessageExtensions.Trace(System.Net.Http.HttpResponseMessage response) Line 49	C#
 	Microsoft.VisualStudio.Services.WebApi.dll!Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.HandleResponse(System.Net.Http.HttpResponseMessage response) Line 799	C#
 	Microsoft.VisualStudio.Services.WebApi.dll!Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(System.Net.Http.HttpRequestMessage message, System.Net.Http.HttpCompletionOption completionOption, object userState, System.Threading.CancellationToken cancellationToken) Line 793	C#
 	[Resuming Async Method]	
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(object stateMachine)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.OutputAsyncCausalityEvents.AnonymousMethod__0()	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.ContinuationWrapper.Invoke()	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.TaskAwaiter.OutputWaitEtwEvents.AnonymousMethod__0()	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.ContinuationWrapper.Invoke()	Unknown
 	mscorlib.dll!System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action action, bool allowInlining, ref System.Threading.Tasks.Task currentTask)	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.FinishContinuations()	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.FinishStageThree()	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task<System.__Canon>.TrySetResult(System.__Canon result)	Unknown
 	mscorlib.dll!System.Threading.Tasks.TaskCompletionSource<System.__Canon>.TrySetResult(System.__Canon result)	Unknown
 	System.Net.Http.dll!System.Net.Http.HttpClient.SetTaskCompleted(System.Net.Http.HttpRequestMessage request, System.Threading.CancellationTokenSource cancellationTokenSource, System.Threading.Tasks.TaskCompletionSource<System.Net.Http.HttpResponseMessage> tcs, System.Net.Http.HttpResponseMessage response)	Unknown
 	System.Net.Http.dll!System.Net.Http.HttpClient.StartContentBuffering.AnonymousMethod__0(System.Threading.Tasks.Task contentTask)	Unknown
 	mscorlib.dll!System.Threading.Tasks.ContinuationTaskFromTask.InnerInvoke()	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.Execute()	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.ExecutionContextCallback(object obj)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.ExecuteWithThreadLocal(ref System.Threading.Tasks.Task currentTaskSlot)	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.ExecuteEntry(bool bPreventDoubleExecution)	Unknown
 	mscorlib.dll!System.Threading.Tasks.ThreadPoolTaskScheduler.TryExecuteTaskInline(System.Threading.Tasks.Task task, bool taskWasPreviouslyQueued)	Unknown
 	mscorlib.dll!System.Threading.Tasks.TaskScheduler.TryRunInline(System.Threading.Tasks.Task task, bool taskWasPreviouslyQueued)	Unknown
 	mscorlib.dll!System.Threading.Tasks.TaskContinuation.InlineIfPossibleOrElseQueue(System.Threading.Tasks.Task task, bool needsProtection)	Unknown
 	mscorlib.dll!System.Threading.Tasks.StandardTaskContinuation.Run(System.Threading.Tasks.Task completedTask, bool bCanInlineContinuationTask)	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.ContinueWithCore(System.Threading.Tasks.Task continuationTask, System.Threading.Tasks.TaskScheduler scheduler, System.Threading.CancellationToken cancellationToken, System.Threading.Tasks.TaskContinuationOptions options)	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.ContinueWith(System.Action<System.Threading.Tasks.Task> continuationAction, System.Threading.Tasks.TaskScheduler scheduler, System.Threading.CancellationToken cancellationToken, System.Threading.Tasks.TaskContinuationOptions continuationOptions, ref System.Threading.StackCrawlMark stackMark)	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.ContinueWith(System.Action<System.Threading.Tasks.Task> continuationAction, System.Threading.CancellationToken cancellationToken, System.Threading.Tasks.TaskContinuationOptions continuationOptions, System.Threading.Tasks.TaskScheduler scheduler)	Unknown
 	System.Net.Http.dll!System.Net.Http.HttpUtilities.ContinueWithStandard(System.Threading.Tasks.Task task, System.Action<System.Threading.Tasks.Task> continuation)	Unknown
 	System.Net.Http.dll!System.Net.Http.HttpClient.StartContentBuffering(System.Net.Http.HttpRequestMessage request, System.Threading.CancellationTokenSource cancellationTokenSource, System.Threading.Tasks.TaskCompletionSource<System.Net.Http.HttpResponseMessage> tcs, System.Net.Http.HttpResponseMessage response)	Unknown
 	System.Net.Http.dll!System.Net.Http.HttpClient.SendAsync.AnonymousMethod__0(System.Threading.Tasks.Task<System.Net.Http.HttpResponseMessage> task)	Unknown
 	mscorlib.dll!System.Threading.Tasks.ContinuationTaskFromResultTask<System.Net.Http.HttpResponseMessage>.InnerInvoke()	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.Execute()	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.ExecutionContextCallback(object obj)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.ExecuteWithThreadLocal(ref System.Threading.Tasks.Task currentTaskSlot)	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.ExecuteEntry(bool bPreventDoubleExecution)	Unknown
 	mscorlib.dll!System.Threading.Tasks.ThreadPoolTaskScheduler.TryExecuteTaskInline(System.Threading.Tasks.Task task, bool taskWasPreviouslyQueued)	Unknown
 	mscorlib.dll!System.Threading.Tasks.TaskScheduler.TryRunInline(System.Threading.Tasks.Task task, bool taskWasPreviouslyQueued)	Unknown
 	mscorlib.dll!System.Threading.Tasks.TaskContinuation.InlineIfPossibleOrElseQueue(System.Threading.Tasks.Task task, bool needsProtection)	Unknown
 	mscorlib.dll!System.Threading.Tasks.StandardTaskContinuation.Run(System.Threading.Tasks.Task completedTask, bool bCanInlineContinuationTask)	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.FinishContinuations()	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.FinishStageThree()	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task<System.__Canon>.TrySetResult(System.__Canon result)	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.Net.Http.HttpResponseMessage>.SetResult(System.Net.Http.HttpResponseMessage result)	Unknown
 	Microsoft.VisualStudio.Services.Common.dll!Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.SendAsync(System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) Line 151	C#
 	[Resuming Async Method]	
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(object stateMachine)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.OutputAsyncCausalityEvents.AnonymousMethod__0()	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.ContinuationWrapper.Invoke()	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.TaskAwaiter.OutputWaitEtwEvents.AnonymousMethod__0()	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.ContinuationWrapper.Invoke()	Unknown
 	mscorlib.dll!System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action action, bool allowInlining, ref System.Threading.Tasks.Task currentTask)	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.FinishContinuations()	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.FinishStageThree()	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task<System.__Canon>.TrySetResult(System.__Canon result)	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.Net.Http.HttpResponseMessage>.SetResult(System.Net.Http.HttpResponseMessage result)	Unknown
 	Microsoft.VisualStudio.Services.Common.dll!Microsoft.VisualStudio.Services.Common.VssHttpMessageHandler.SendAsync(System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) Line 394	C#
 	kernel32.dll!BaseThreadInitThunk(unsigned long RunProcessInit, long(__stdcall*)(void *) StartAddress, void * Argument) Line 64	C
 	ntdll.dll!__RtlUserThreadStart()	Unknown
 	ntdll.dll!__RtlUserThreadStart@8()	Unknown
 	[Resuming Async Method]	
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(object stateMachine)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.OutputAsyncCausalityEvents.AnonymousMethod__0()	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.ContinuationWrapper.Invoke()	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.TaskAwaiter.OutputWaitEtwEvents.AnonymousMethod__0()	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.ContinuationWrapper.Invoke()	Unknown
 	mscorlib.dll!System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action action, bool allowInlining, ref System.Threading.Tasks.Task currentTask)	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.FinishContinuations()	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.FinishStageThree()	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task<System.__Canon>.TrySetResult(System.__Canon result)	Unknown
 	mscorlib.dll!System.Threading.Tasks.TaskCompletionSource<System.__Canon>.TrySetResult(System.__Canon result)	Unknown
 	System.Net.Http.dll!System.Net.Http.HttpClientHandler.GetResponseCallback(System.IAsyncResult ar)	Unknown
 	System.dll!System.Net.LazyAsyncResult.Complete(System.IntPtr userToken)	Unknown
 	System.dll!System.Net.ContextAwareResult.CompleteCallback(object state)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state)	Unknown
 	System.dll!System.Net.ContextAwareResult.Complete(System.IntPtr userToken)	Unknown
 	System.dll!System.Net.LazyAsyncResult.ProtectedInvokeCallback(object result, System.IntPtr userToken)	Unknown
 	System.dll!System.Net.HttpWebRequest.ProcessResponse()	Unknown
 	System.dll!System.Net.HttpWebRequest.SetResponse(System.Net.CoreResponseData coreResponseData)	Unknown
 	System.dll!System.Net.HttpWebRequest.SetAndOrProcessResponse(object responseOrException)	Unknown
 	System.dll!System.Net.ConnectionReturnResult.SetResponses(System.Net.ConnectionReturnResult returnResult)	Unknown
 	System.dll!System.Net.Connection.ReadComplete(int bytesRead, System.Net.WebExceptionStatus errorStatus)	Unknown
 	System.dll!System.Net.Connection.ReadCallback(System.IAsyncResult asyncResult)	Unknown
 	System.dll!System.Net.Connection.ReadCallbackWrapper(System.IAsyncResult asyncResult)	Unknown
 	System.dll!System.Net.LazyAsyncResult.Complete(System.IntPtr userToken)	Unknown
 	System.dll!System.Net.LazyAsyncResult.ProtectedInvokeCallback(object result, System.IntPtr userToken)	Unknown
 	System.dll!System.Net.Security._SslStream.ProcessFrameBody(int readBytes, byte[] buffer, int offset, int count, System.Net.AsyncProtocolRequest asyncRequest)	Unknown
 	System.dll!System.Net.Security._SslStream.ReadFrameCallback(System.Net.AsyncProtocolRequest asyncRequest)	Unknown
 	System.dll!System.Net.AsyncProtocolRequest.CompleteRequest(int result)	Unknown
 	System.dll!System.Net.FixedSizeReader.CheckCompletionBeforeNextRead(int bytes)	Unknown
 	System.dll!System.Net.FixedSizeReader.ReadCallback(System.IAsyncResult transportResult)	Unknown
 	System.dll!System.Net.LazyAsyncResult.Complete(System.IntPtr userToken)	Unknown
 	System.dll!System.Net.ContextAwareResult.CompleteCallback(object state)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state)	Unknown
 	System.dll!System.Net.ContextAwareResult.Complete(System.IntPtr userToken)	Unknown
 	System.dll!System.Net.LazyAsyncResult.ProtectedInvokeCallback(object result, System.IntPtr userToken)	Unknown
 	System.dll!System.Net.Sockets.BaseOverlappedAsyncResult.CompletionPortCallback(uint errorCode, uint numBytes, System.Threading.NativeOverlapped* nativeOverlapped)	Unknown
 	mscorlib.dll!System.Threading._IOCompletionCallback.PerformIOCompletionCallback(uint errorCode, uint numBytes, System.Threading.NativeOverlapped* pOVERLAP)	Unknown
 	[Native to Managed Transition]	
 	[Async Call]	
 	Microsoft.VisualStudio.Services.WebApi.dll!Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync<System.Collections.Generic.IList<Microsoft.VisualStudio.Services.Profile.ProfileAttributeBase<object>>>(System.Net.Http.HttpRequestMessage message, object userState, System.Threading.CancellationToken cancellationToken) Line 688	C#
 	[Async Call]	
 	Microsoft.VisualStudio.Services.WebApi.dll!Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync<System.Collections.Generic.IList<Microsoft.VisualStudio.Services.Profile.ProfileAttributeBase<object>>>(System.Net.Http.HttpMethod method, System.Collections.Generic.IEnumerable<System.Collections.Generic.KeyValuePair<string, string>> additionalHeaders, System.Guid locationId, object routeValues, Microsoft.VisualStudio.Services.WebApi.ApiResourceVersion version, System.Net.Http.HttpContent content, System.Collections.Generic.IEnumerable<System.Collections.Generic.KeyValuePair<string, string>> queryParameters, object userState, System.Threading.CancellationToken cancellationToken) Line 383	C#
 	[Async Call]	
 	Microsoft.VisualStudio.Services.WebApi.dll!Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync<System.Collections.Generic.IList<Microsoft.VisualStudio.Services.Profile.ProfileAttributeBase<object>>>(System.Net.Http.HttpMethod method, System.Guid locationId, object routeValues, Microsoft.VisualStudio.Services.WebApi.ApiResourceVersion version, System.Net.Http.HttpContent content, System.Collections.Generic.IEnumerable<System.Collections.Generic.KeyValuePair<string, string>> queryParameters, object userState, System.Threading.CancellationToken cancellationToken) Line 366	C#
 	[Async Call]	
 	Microsoft.VisualStudio.Services.WebApi.dll!Microsoft.VisualStudio.Services.Profile.Client.ProfileHttpClientBase.GetAttributesInternalAsync(Microsoft.VisualStudio.Services.Profile.AttributesQueryContext attributesQueryContext, string id, object userState, System.Threading.CancellationToken cancellationToken) Line 364	C#
 	[Async Call]	
 	Microsoft.VisualStudio.Services.WebApi.dll!Microsoft.VisualStudio.Services.Profile.Client.ProfileHttpClientBase.GetAttributesAsync(Microsoft.VisualStudio.Services.Profile.AttributesQueryContext attributesQueryContext, string id, object userState, System.Threading.CancellationToken cancellationToken) Line 377	C#
 	[Async Call]	
 	Microsoft.VisualStudio.Shell.Connected.dll!Microsoft.VisualStudio.Shell.Connected.ConnectedUser.IdeUserSession.Microsoft.VisualStudio.Shell.Connected.ConnectedUser.IOnlineSettingsSupport.GetProfileAttributesAsync(Microsoft.VisualStudio.Services.Profile.AttributesQueryContext queryContext, Microsoft.VisualStudio.Shell.Connected.ConnectedUser.RefreshReason reason) Line 432	C#
 	[Async Call]	
 	Microsoft.VisualStudio.Shell.Connected.dll!Microsoft.VisualStudio.Shell.Connected.ConnectedUser.VsOnlineSettings.RefreshAsyncImpl(Microsoft.VisualStudio.Shell.Connected.ConnectedUser.RefreshReason reason, int modifiedAfterRevision) Line 500	C#
 	[Async Call]	
 	Microsoft.VisualStudio.Shell.Connected.dll!Microsoft.VisualStudio.Shell.Connected.ConnectedUser.VsOnlineSettings.RefreshAsync(Microsoft.VisualStudio.Shell.Connected.ConnectedUser.RefreshReason reason, int? modifiedAfterRevision) Line 465	C#
 	Microsoft.VisualStudio.Shell.Connected.dll!Microsoft.VisualStudio.Shell.Connected.ConnectedUser.VsOnlineSettings.RefreshAsync(Microsoft.VisualStudio.Shell.Connected.ConnectedUser.RefreshReason reason, int? modifiedAfterRevision) Line 453	C#

**Comment by madskristensen** [comment]
Fixed

**Comment by somewhatabstract** [comment]
I am still experiencing this with release 1.0.8

**Comment by modulexcite** [comment]
Thank you @madskristensen for yet another excellent extension.
I'm experiencing this issue with Visual Studio 2017 15.5.6 and Debug Trace Logger 1.08 on Windows 10 Fall Creators Update.
